publish

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,61 +23,75 @@ jobs:
     
     publish:
         needs: [build]
-        runs-on: ubuntu-latest
-        environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
-        env:
-            IMAGE_REPO: "${{ github.repository }}/${{ github.ref_name }}"
-            URI_ECR: "${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"
-            MULTI_PLATFORM: 'false'
-        steps:
-            - uses: actions/checkout@v4
+        uses: org-sam-2/templates-ci/.github/workflows/publish-aws-ecr.yaml@main
+        with:
+          runs_on: ubuntu-latest
+          environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
+          downloaded_name_artifacts: artifacts
+          dockerfile: ./Dockerfile
+          docker_build_context: ./
+          docker_push_ecr: true
+          hadolint_no_fail: true
+          aws_role_to_assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-oicd
+          aws_region: us-east-1
+          multi_platform: 'false'
+
+        # needs: [build]
+        # runs-on: ubuntu-latest
+        # environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
+        # env:
+        #     IMAGE_REPO: "${{ github.repository }}/${{ github.ref_name }}"
+        #     URI_ECR: "${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"
+        #     MULTI_PLATFORM: 'false'
+        # steps:
+        #     - uses: actions/checkout@v4
             
-            - uses: actions/download-artifact@v4
-              with:
-                name: build-artifact
-                path: artifacts
+        #     - uses: actions/download-artifact@v4
+        #       with:
+        #         name: build-artifact
+        #         path: artifacts
             
-            - name: Analyze Dockerfile
-              uses: hadolint/hadolint-action@v3.1.0
-              with:
-                  dockerfile: ./Dockerfile
-                  no-fail: true
+        #     - name: Analyze Dockerfile
+        #       uses: hadolint/hadolint-action@v3.1.0
+        #       with:
+        #           dockerfile: ./Dockerfile
+        #           no-fail: true
             
-            - name: Configure AWS credentials
-              uses: aws-actions/configure-aws-credentials@v4
-              with:
-                role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-oicd
-                aws-region: ${{ vars.AWS_REGION }}
+        #     - name: Configure AWS credentials
+        #       uses: aws-actions/configure-aws-credentials@v4
+        #       with:
+        #         role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-oicd
+        #         aws-region: ${{ vars.AWS_REGION }}
     
-            - name: Login to Amazon ECR
-              uses: aws-actions/amazon-ecr-login@v2
+        #     - name: Login to Amazon ECR
+        #       uses: aws-actions/amazon-ecr-login@v2
 
-            - name: Ensure ECR Repository Exists
-              run: |
-                aws ecr describe-repositories --repository-names "${{ env.IMAGE_REPO }}" || \
-                aws ecr create-repository --repository-name "${{ env.IMAGE_REPO }}"
+        #     - name: Ensure ECR Repository Exists
+        #       run: |
+        #         aws ecr describe-repositories --repository-names "${{ env.IMAGE_REPO }}" || \
+        #         aws ecr create-repository --repository-name "${{ env.IMAGE_REPO }}"
             
-            - name: Set up QEMU
-              uses: docker/setup-qemu-action@v3
-              if: ${{ env.MULTI_PLATFORM == 'true' }}
+        #     - name: Set up QEMU
+        #       uses: docker/setup-qemu-action@v3
+        #       if: ${{ env.MULTI_PLATFORM == 'true' }}
 
-            - name: Set up Docker Buildx
-              uses: docker/setup-buildx-action@v3
-              if: ${{ env.MULTI_PLATFORM == 'true' }}
+        #     - name: Set up Docker Buildx
+        #       uses: docker/setup-buildx-action@v3
+        #       if: ${{ env.MULTI_PLATFORM == 'true' }}
 
-            - name: Set platforms
-              run: |
-                echo "PLATFORMS=$( [ '${{ env.MULTI_PLATFORM }}' == 'true' ] && echo 'linux/amd64,linux/arm64' || echo 'linux/amd64' )" >> $GITHUB_ENV
+        #     - name: Set platforms
+        #       run: |
+        #         echo "PLATFORMS=$( [ '${{ env.MULTI_PLATFORM }}' == 'true' ] && echo 'linux/amd64,linux/arm64' || echo 'linux/amd64' )" >> $GITHUB_ENV
             
-            - name: Push Docker image to ECR
-              uses: docker/build-push-action@v4
-              with:
-                context: .
-                push: true
-                platforms: ${{ env.PLATFORMS }}
-                tags: |
-                    ${{ env.URI_ECR }}/${{ env.IMAGE_REPO }}:${{ github.run_id }}
-                    ${{ env.URI_ECR }}/${{ env.IMAGE_REPO }}:latest
+        #     - name: Push Docker image to ECR
+        #       uses: docker/build-push-action@v4
+        #       with:
+        #         context: .
+        #         push: true
+        #         platforms: ${{ env.PLATFORMS }}
+        #         tags: |
+        #             ${{ env.URI_ECR }}/${{ env.IMAGE_REPO }}:${{ github.run_id }}
+        #             ${{ env.URI_ECR }}/${{ env.IMAGE_REPO }}:latest
     
 
     # publish:
